# Generated by Django 5.2.1 on 2025-05-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
